version: "3"

services:
    flask_vrp_dev:
        image: flask_vrp_dev:1.00
        container_name: flask_vrp_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ..:/usr/app